In [1]:
import pandas as pd

base = pd.read_csv('census.csv')

base

age          workclass  final-weight    education  education-num  \
0       39          State-gov         77516    Bachelors             13   
1       50   Self-emp-not-inc         83311    Bachelors             13   
2       38            Private        215646      HS-grad              9   
3       53            Private        234721         11th              7   
4       28            Private        338409    Bachelors             13   
...    ...                ...           ...          ...            ...   
32556   27            Private        257302   Assoc-acdm             12   
32557   40            Private        154374      HS-grad              9   
32558   58            Private        151910      HS-grad              9   
32559   22            Private        201490      HS-grad              9   
32560   52       Self-emp-inc        287927      HS-grad              9   

            marital-status          occupation    relationship    race  \
0            Never-married        Adm-clerical   Not-in-family   White   
1       Married-civ-spouse     Exec-managerial         Husband   White   
2                 Divorced   Handlers-cleaners   Not-in-family   White   
3       Married-civ-spouse   Handlers-cleaners         Husband   Black   
4       Married-civ-spouse      Prof-specialty            Wife   Black   
...                    ...                 ...             ...     ...   
32556   Married-civ-spouse        Tech-support            Wife   White   
32557   Married-civ-spouse   Machine-op-inspct         Husband   White   
32558              Widowed        Adm-clerical       Unmarried   White   
32559        Never-married        Adm-clerical       Own-child   White   
32560   Married-civ-spouse     Exec-managerial            Wife   White   

           sex  capital-gain  capital-loos  hour-per-week  native-country  \
0         Male          2174             0             40   United-States   
1         Male             0             0             13   United-States   
2         Male             0             0             40   United-States   
3         Male             0             0             40   United-States   
4       Female             0             0             40            Cuba   
...        ...           ...           ...            ...             ...   
32556   Female             0             0             38   United-States   
32557     Male             0             0             40   United-States   
32558   Female             0             0             40   United-States   
32559     Male             0             0             20   United-States   
32560   Female         15024             0             40   United-States   

       income  
0       <=50K  
1       <=50K  
2       <=50K  
3       <=50K  
4       <=50K  
...       ...  
32556   <=50K  
32557    >50K  
32558   <=50K  
32559   <=50K  
32560    >50K  

[32561 rows x 15 columns]

In [2]:
colunas = base.columns[:-1]
colunas

Index(['age', 'workclass', 'final-weight', 'education', 'education-num',
       'marital-status', 'occupation', 'relationship', 'race', 'sex',
       'capital-gain', 'capital-loos', 'hour-per-week', 'native-country'],
      dtype='object')

In [3]:
X_census = base.iloc[:, 0:14].values
Y_census = base.iloc[:, 14].values

In [4]:
X_census

array([[39, ' State-gov', 77516, ..., 0, 40, ' United-States'],
       [50, ' Self-emp-not-inc', 83311, ..., 0, 13, ' United-States'],
       [38, ' Private', 215646, ..., 0, 40, ' United-States'],
       ...,
       [58, ' Private', 151910, ..., 0, 40, ' United-States'],
       [22, ' Private', 201490, ..., 0, 20, ' United-States'],
       [52, ' Self-emp-inc', 287927, ..., 0, 40, ' United-States']],
      dtype=object)

In [5]:
Y_census

array([' <=50K', ' <=50K', ' <=50K', ..., ' <=50K', ' <=50K', ' >50K'],
      dtype=object)

In [6]:
#LABEL ENCODER

from sklearn.preprocessing import LabelEncoder
label_encoder_workclass = LabelEncoder()
label_encoder_education = LabelEncoder()
label_encoder_marital = LabelEncoder()
label_encoder_occupation = LabelEncoder()
label_encoder_relationship = LabelEncoder()
label_encoder_race = LabelEncoder()
label_encoder_sex = LabelEncoder()
label_encoder_country = LabelEncoder()

X_census[:,1] = label_encoder_workclass.fit_transform(X_census[:,1])
X_census[:,3] = label_encoder_education.fit_transform(X_census[:,3])
X_census[:,5] = label_encoder_marital.fit_transform(X_census[:,5])
X_census[:,6] = label_encoder_occupation.fit_transform(X_census[:,6])
X_census[:,7] = label_encoder_relationship.fit_transform(X_census[:,7])
X_census[:,8] = label_encoder_race.fit_transform(X_census[:,8])
X_census[:,9] = label_encoder_sex.fit_transform(X_census[:,9])
X_census[:,13] = label_encoder_country.fit_transform(X_census[:,13])

In [7]:
X_census

array([[39, 7, 77516, ..., 0, 40, 39],
       [50, 6, 83311, ..., 0, 13, 39],
       [38, 4, 215646, ..., 0, 40, 39],
       ...,
       [58, 4, 151910, ..., 0, 40, 39],
       [22, 4, 201490, ..., 0, 20, 39],
       [52, 5, 287927, ..., 0, 40, 39]], dtype=object)

In [8]:
#Normalização

from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler() #Pode ser também a padronização StandardScaler() com DesvioPadrao se tivesse Outliers na base
Xescalado = scaler.fit_transform(X_census)
Xescalado

array([[0.30136986, 0.875     , 0.0443019 , ..., 0.        , 0.39795918,
        0.95121951],
       [0.45205479, 0.75      , 0.0482376 , ..., 0.        , 0.12244898,
        0.95121951],
       [0.28767123, 0.5       , 0.13811345, ..., 0.        , 0.39795918,
        0.95121951],
       ...,
       [0.56164384, 0.5       , 0.09482688, ..., 0.        , 0.39795918,
        0.95121951],
       [0.06849315, 0.5       , 0.12849934, ..., 0.        , 0.19387755,
        0.95121951],
       [0.47945205, 0.625     , 0.18720338, ..., 0.        , 0.39795918,
        0.95121951]])

LOW VARIANCE - BASEADO EM MEDIDA DE DISPERSÃO ESTATÍSTICA, COM BASE EM VARIANCIA. LEMBRANDO, É A DISTANCIA DA MÉDIA

In [9]:
for item in range(X_census.shape[1]): #SHAPE [1] colunas
    print(Xescalado[:, item].var()) #extração da variancia para cada atributo

0.034913808595952486
0.03312115190663569
0.005138537590667898
0.06657103564450892
0.029416385024073417
0.06301761677301636
0.09123816653931152
0.10326534394406342
0.04502805169292987
0.22136950173699113
0.00545419549240862
0.008557270623428908
0.015874043397822807
0.03641266114220053


In [10]:
from re import X
from sklearn.feature_selection import VarianceThreshold
#LIMIAR DE VARIANCIA
#NOTE QUE VALORES BAIXOS, SÃO VALORES QUE SE APROXIMAM DA MÉDIA
#BUSCAMOS VALORES ALTOS NESTE CASO
selecao = VarianceThreshold(threshold=0.05)
X_census_variancia = selecao.fit_transform(Xescalado)
X_census_variancia.shape

(32561, 5)

In [11]:
X_census_variancia #Colunas reduzidas, devido a escolha baseada em variancia

array([[0.6       , 0.66666667, 0.07142857, 0.2       , 1.        ],
       [0.6       , 0.33333333, 0.28571429, 0.        , 1.        ],
       [0.73333333, 0.        , 0.42857143, 0.2       , 1.        ],
       ...,
       [0.73333333, 1.        , 0.07142857, 0.8       , 0.        ],
       [0.73333333, 0.66666667, 0.07142857, 0.6       , 1.        ],
       [0.73333333, 0.33333333, 0.28571429, 1.        , 0.        ]])

In [12]:
selecao.variances_ #SAO AS MESMAS VARIANCIAS

array([0.03491381, 0.03312115, 0.00513854, 0.06657104, 0.02941639,
       0.06301762, 0.09123817, 0.10326534, 0.04502805, 0.2213695 ,
       0.0054542 , 0.00855727, 0.01587404, 0.03641266])

In [13]:
import numpy as np
indices = np.where(selecao.variances_ > 0.05)
indices #MOSTRANDO QUAIS ATRIBUTOS FORAM SELECIONADOS

(array([3, 5, 6, 7, 9]),)

In [14]:
colunas[indices]

Index(['education', 'marital-status', 'occupation', 'relationship', 'sex'], dtype='object')

In [15]:
baseNova = base.drop(columns = ['age', 'workclass', 'final-weight', 'education-num',
                                'race', 'capital-gain', 'capital-loos', 'hour-per-week', 'native-country'], axis = 1)

In [16]:
baseNova

education       marital-status          occupation    relationship  \
0        Bachelors        Never-married        Adm-clerical   Not-in-family   
1        Bachelors   Married-civ-spouse     Exec-managerial         Husband   
2          HS-grad             Divorced   Handlers-cleaners   Not-in-family   
3             11th   Married-civ-spouse   Handlers-cleaners         Husband   
4        Bachelors   Married-civ-spouse      Prof-specialty            Wife   
...            ...                  ...                 ...             ...   
32556   Assoc-acdm   Married-civ-spouse        Tech-support            Wife   
32557      HS-grad   Married-civ-spouse   Machine-op-inspct         Husband   
32558      HS-grad              Widowed        Adm-clerical       Unmarried   
32559      HS-grad        Never-married        Adm-clerical       Own-child   
32560      HS-grad   Married-civ-spouse     Exec-managerial            Wife   

           sex  income  
0         Male   <=50K  
1         Male   <=50K  
2         Male   <=50K  
3         Male   <=50K  
4       Female   <=50K  
...        ...     ...  
32556   Female   <=50K  
32557     Male    >50K  
32558   Female   <=50K  
32559     Male   <=50K  
32560   Female    >50K  

[32561 rows x 6 columns]

In [17]:
treinoAtributos = baseNova.iloc[:, 0:5].values
testeAtributos = baseNova.iloc[:, 5].values

In [18]:
treinoAtributos

array([[' Bachelors', ' Never-married', ' Adm-clerical',
        ' Not-in-family', ' Male'],
       [' Bachelors', ' Married-civ-spouse', ' Exec-managerial',
        ' Husband', ' Male'],
       [' HS-grad', ' Divorced', ' Handlers-cleaners', ' Not-in-family',
        ' Male'],
       ...,
       [' HS-grad', ' Widowed', ' Adm-clerical', ' Unmarried', ' Female'],
       [' HS-grad', ' Never-married', ' Adm-clerical', ' Own-child',
        ' Male'],
       [' HS-grad', ' Married-civ-spouse', ' Exec-managerial', ' Wife',
        ' Female']], dtype=object)

In [19]:
testeAtributos

array([' <=50K', ' <=50K', ' <=50K', ..., ' <=50K', ' <=50K', ' >50K'],
      dtype=object)

In [20]:
treinoAtributos[:, 0] = label_encoder_education.fit_transform(treinoAtributos[:,0])
treinoAtributos[:, 1] = label_encoder_marital.fit_transform(treinoAtributos[:,1])
treinoAtributos[:, 2] = label_encoder_occupation.fit_transform(treinoAtributos[:,2])
treinoAtributos[:, 3] = label_encoder_relationship.fit_transform(treinoAtributos[:,3])
treinoAtributos[:, 4] = label_encoder_sex.fit_transform(treinoAtributos[:,4])

In [21]:
treinoAtributos

array([[9, 4, 1, 1, 1],
       [9, 2, 4, 0, 1],
       [11, 0, 6, 1, 1],
       ...,
       [11, 6, 1, 4, 0],
       [11, 4, 1, 3, 1],
       [11, 2, 4, 5, 0]], dtype=object)

In [22]:
#ONE HOT ENCODER
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

onehot = ColumnTransformer(transformers=[('OneHot', OneHotEncoder(), [0,1,2,3,4])], remainder='passthrough')

treinoAtributos = onehot.fit_transform(treinoAtributos).toarray()

treinoAtributos

array([[0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 1.],
       ...,
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 1., 1., 0.]])

In [23]:

scaler = MinMaxScaler() #Pode ser também a padronização StandardScaler() com DesvioPadrao se tivesse Outliers na base
treinoAtributosEscalado = scaler.fit_transform(treinoAtributos)
treinoAtributosEscalado

array([[0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 1.],
       ...,
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 1., 1., 0.]])

In [24]:
#APLICANDO O SPLIT

from sklearn.model_selection import train_test_split

#X se refere ao atributos previsores
#Y se refere ao atributo alvo da classificação
X_treinamento, X_teste, y_treinamento, y_teste = train_test_split(treinoAtributosEscalado, testeAtributos, test_size= 0.25, random_state=0)

In [25]:
X_treinamento.shape, X_teste.shape #SEM ESSA TECNICA, TINHAMOS ANTERIORMENTE 108

((24420, 46), (8141, 46))

In [26]:
from sklearn.ensemble import RandomForestClassifier
random_forest_credit = RandomForestClassifier(n_estimators = 40, criterion = 'entropy', random_state = 0)

random_forest_credit.fit(X_treinamento,y_treinamento)

RandomForestClassifier(criterion='entropy', n_estimators=40, random_state=0)

In [27]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

previsoes = random_forest_credit.predict(X_teste)
accuracy_score(y_teste, previsoes)

0.8216435327355361

EXTRA TREE

In [28]:
from sklearn.ensemble import ExtraTreesClassifier

In [29]:
Xescalado.shape

(32561, 14)

In [31]:
selecao = ExtraTreesClassifier()

selecao.fit(Xescalado, Y_census)

ExtraTreesClassifier()

In [34]:
importancias = selecao.feature_importances_
importancias #Maior valor é o atributo mais importante conforme a entropia da informação

array([0.15485919, 0.04553455, 0.16426076, 0.03654792, 0.08668557,
       0.06641827, 0.07453196, 0.0917476 , 0.01455336, 0.03130748,
       0.093313  , 0.0291341 , 0.09342273, 0.01768353])

In [35]:
colunas

Index(['age', 'workclass', 'final-weight', 'education', 'education-num',
       'marital-status', 'occupation', 'relationship', 'race', 'sex',
       'capital-gain', 'capital-loos', 'hour-per-week', 'native-country'],
      dtype='object')

In [36]:
importancias.sum()

1.0

In [37]:
indices = []

for i in range(len(importancias)):
  if importancias[i] >= 0.029:
    indices.append(i)

indices

[0, 1, 2, 3, 4, 5, 6, 7, 9, 10, 11, 12]

In [38]:
colunas[indices]

Index(['age', 'workclass', 'final-weight', 'education', 'education-num',
       'marital-status', 'occupation', 'relationship', 'sex', 'capital-gain',
       'capital-loos', 'hour-per-week'],
      dtype='object')

In [62]:
XExtra = X_census[:, indices]

XExtra

array([[39, 7, 77516, ..., 2174, 0, 40],
       [50, 6, 83311, ..., 0, 0, 13],
       [38, 4, 215646, ..., 0, 0, 40],
       ...,
       [58, 4, 151910, ..., 0, 0, 40],
       [22, 4, 201490, ..., 0, 0, 20],
       [52, 5, 287927, ..., 15024, 0, 40]], dtype=object)

In [63]:
#ONE HOT ENCODER
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

onehot = ColumnTransformer(transformers=[('OneHot', OneHotEncoder(), [1,3,5,6,7])], remainder='passthrough')

XExtra = onehot.fit_transform(XExtra).toarray()

XExtra

array([[0.0000e+00, 0.0000e+00, 0.0000e+00, ..., 2.1740e+03, 0.0000e+00,
        4.0000e+01],
       [0.0000e+00, 0.0000e+00, 0.0000e+00, ..., 0.0000e+00, 0.0000e+00,
        1.3000e+01],
       [0.0000e+00, 0.0000e+00, 0.0000e+00, ..., 0.0000e+00, 0.0000e+00,
        4.0000e+01],
       ...,
       [0.0000e+00, 0.0000e+00, 0.0000e+00, ..., 0.0000e+00, 0.0000e+00,
        4.0000e+01],
       [0.0000e+00, 0.0000e+00, 0.0000e+00, ..., 0.0000e+00, 0.0000e+00,
        2.0000e+01],
       [0.0000e+00, 0.0000e+00, 0.0000e+00, ..., 1.5024e+04, 0.0000e+00,
        4.0000e+01]])

In [64]:
XExtra.shape

(32561, 60)

In [71]:
#APLICANDO O SPLIT

from sklearn.model_selection import train_test_split

#X se refere ao atributos previsores
#Y se refere ao atributo alvo da classificação
X_treinamentoExtra, X_testeExtra, y_treinamentoExtra, y_testeExtra = train_test_split(XExtra, testeAtributos, test_size= 0.25, random_state=0)
X_treinamentoExtra.shape, X_testeExtra.shape

((24420, 60), (8141, 60))

In [72]:
from sklearn.ensemble import RandomForestClassifier
random_forest_credit = RandomForestClassifier(n_estimators = 40, min_samples_leaf=1, min_samples_split=5, criterion = 'entropy', random_state = 0)

random_forest_credit.fit(X_treinamentoExtra,y_treinamentoExtra)

RandomForestClassifier(criterion='entropy', min_samples_split=5,
                       n_estimators=40, random_state=0)

In [74]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

previsoes = random_forest_credit.predict(X_testeExtra)
accuracy_score(y_testeExtra, previsoes)

0.8545633214592802