In [2]:
!pip install plotly --upgrade
import plotly.express as px
import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import plotly.graph_objects as go
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error, mean_squared_error
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVR

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.4/16.4 MB 47.1 MB/s eta 0:00:00
  Attempting uninstall: plotly
    Found existing installation: plotly 5.15.0
    Uninstalling plotly-5.15.0:
      Successfully uninstalled plotly-5.15.0


In [ ]:
base1 = pd.read_csv('plano_saude2.csv')
X = base1.iloc[:, 0:1].values
Y = base1.iloc[:, 1].values

In [ ]:
X

array([[18],
       [23],
       [28],
       [33],
       [38],
       [43],
       [48],
       [53],
       [58],
       [63]])

In [ ]:
#KERNEL LINEAR

regressor = SVR(kernel = 'linear')
regressor.fit(X,Y)
regressor.score(X,Y) #Coeficiente de determinação

0.294299767185203

In [ ]:
grafico = px.scatter(x = X.ravel(), y = Y) #GRAFICO DE DISPERSÃO
grafico.add_scatter(x = X.ravel(), y = regressor.predict(X), name = 'Regressão Arvore')
grafico.show()

In [ ]:
#KERNEL POLINOMIAL

regressor = SVR(kernel = 'poly', degree=3) #degree - Versao original, ao quadrado e ao  cubo
regressor.fit(X,Y)
regressor.score(X,Y)


0.6697433307984383

In [ ]:
grafico = px.scatter(x = X.ravel(), y = Y) #GRAFICO DE DISPERSÃO
grafico.add_scatter(x = X.ravel(), y = regressor.predict(X), name = 'Regressão Arvore')
grafico.show()

In [ ]:
#KERNEL RBF
novoX = StandardScaler() #COLOCANDO TUDO NA MESMA ESCALA
X = novoX.fit_transform(X)
novoY = StandardScaler()
Y = novoY.fit_transform(Y.reshape(-1,1))


regressor = SVR(kernel = 'rbf')
regressor.fit(X,Y.ravel())
regressor.score(X,Y) #Coeficiente de determinação

0.7561578176049304

In [ ]:
grafico = px.scatter(x = X.ravel(), y = Y.ravel()) #GRAFICO DE DISPERSÃO
grafico.add_scatter(x = X.ravel(), y = regressor.predict(X), name = 'Regressão Arvore')
grafico.show()

In [ ]:
#FAZENDO UMA PREVISÃO
novo = [[40]]
novo

[[40]]

In [ ]:
novo1 = novoX.transform(novo)
novo1

array([[40.]])

In [ ]:
regressor.predict(novo1)

array([0.01359678])

In [ ]:
novoY.inverse_transform(regressor.predict(novo1).reshape(-1,1))

array([[0.01359678]])

BASE DE CASAS


In [13]:
base = pd.read_csv('house_prices.csv')
base.drop('date', axis='columns', inplace=True) #REMOVENDO A COLUNA EM FORMATO DE DATA
X_casas = base.iloc[:,2:18].values
y_casas = base.iloc[:,1].values
XcasasTreino, XcasasTeste, YcasasTreino, YcasasTeste = train_test_split(X_casas,y_casas, test_size = 0.3, random_state=0)
XcasasTreino,YcasasTreino

(array([[ 4.00000e+00,  1.50000e+00,  1.39000e+03, ...,  9.81330e+04,
          4.77224e+01, -1.22332e+02],
        [ 3.00000e+00,  1.50000e+00,  1.45000e+03, ...,  9.81330e+04,
          4.77725e+01, -1.22349e+02],
        [ 5.00000e+00,  2.75000e+00,  2.86000e+03, ...,  9.80520e+04,
          4.77082e+01, -1.22104e+02],
        ...,
        [ 3.00000e+00,  2.25000e+00,  2.36000e+03, ...,  9.80420e+04,
          4.73856e+01, -1.22158e+02],
        [ 4.00000e+00,  2.00000e+00,  2.37000e+03, ...,  9.80010e+04,
          4.72831e+01, -1.22279e+02],
        [ 4.00000e+00,  2.25000e+00,  2.38000e+03, ...,  9.80080e+04,
          4.76126e+01, -1.22120e+02]]),
 array([400000., 430000., 720000., ..., 431000., 411000., 699900.]))

In [14]:
scalerX = StandardScaler()
XcasasTreino = scalerX.fit_transform(XcasasTreino)
scalerY = StandardScaler()
YcasasTreino = scalerY.fit_transform(YcasasTreino.reshape(-1,1))
XcasasTreino,YcasasTreino

(array([[ 0.67170039, -0.79711466, -0.74522967, ...,  1.03727271,
          1.17348387, -0.83797629],
        [-0.38696772, -0.79711466, -0.68028398, ...,  1.03727271,
          1.53476983, -0.95879989],
        [ 1.7303685 ,  0.82292131,  0.84593978, ..., -0.48008241,
          1.07108346,  0.78248142],
        ...,
        [-0.38696772,  0.17490692,  0.30472568, ..., -0.66741021,
         -1.25528083,  0.3986888 ],
        [ 0.67170039, -0.14910028,  0.31554996, ..., -1.43545415,
         -1.99443873, -0.46129094],
        [ 0.67170039,  0.17490692,  0.32637425, ..., -1.3043247 ,
          0.38168351,  0.66876509]]),
 array([[-0.38454326],
        [-0.3024967 ],
        [ 0.49062008],
        ...,
        [-0.29976181],
        [-0.35445952],
        [ 0.43564888]]))

In [15]:
XcasasTeste = scalerX.transform(XcasasTeste)
YcasasTeste = scalerY.transform(YcasasTeste.reshape(-1,1))
XcasasTeste,YcasasTeste

(array([[-1.44563583, -0.79711466, -0.70193254, ...,  0.88741047,
          1.17204161, -0.53947092],
        [ 0.67170039,  1.47093569,  2.80513482, ..., -1.36052304,
          0.54321655,  0.35604518],
        [-1.44563583, -1.76913625, -0.69110826, ...,  0.55022044,
          0.80065984, -1.06540895],
        ...,
        [-0.38696772,  0.49891411,  0.07741576, ..., -0.36768574,
         -0.78077751,  0.88909048],
        [-0.38696772, -0.47310747, -0.64781113, ..., -0.854738  ,
         -1.39878563, -0.46839822],
        [-0.38696772, -1.44512905, -0.82099964, ...,  0.26922876,
         -1.78603226,  0.22100704]]),
 array([[-0.66623646],
        [ 2.83715179],
        [ 0.05878167],
        ...,
        [-0.43924097],
        [-0.74554814],
        [-0.91511104]]))

In [16]:
regressor = SVR(kernel='rbf')

regressor.fit(XcasasTreino,YcasasTreino)

/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVR()

In [17]:
regressor.score(XcasasTreino,YcasasTreino)

0.8123337393146999

In [18]:
regressor.score(XcasasTeste,YcasasTeste)

0.7374454724624955

In [19]:
previsoes = regressor.predict(XcasasTeste)
previsoes

array([-0.54571552,  3.46454238,  0.02286424, ..., -0.46405796,
       -0.91113329, -1.03334346])

In [20]:
YcasasTeste

array([[-0.66623646],
       [ 2.83715179],
       [ 0.05878167],
       ...,
       [-0.43924097],
       [-0.74554814],
       [-0.91511104]])

In [25]:
inversoY = scalerY.inverse_transform(YcasasTeste)
inversoY

array([[ 297000.],
       [1578000.],
       [ 562100.],
       ...,
       [ 380000.],
       [ 268000.],
       [ 206000.]])

In [26]:
invernoPrevisoes = scalerY.inverse_transform(previsoes.reshape(-1,1))
invernoPrevisoes

array([[ 341068.00437506],
       [1807402.87779178],
       [ 548966.93331462],
       ...,
       [ 370925.76457821],
       [ 207454.44649635],
       [ 162768.78477289]])

In [27]:
mean_absolute_error(inversoY,invernoPrevisoes) #pode errar 82 mil dolares para cima ou para baixo

82453.02198930961