In [5]:
!pip install plotly --upgrade
import plotly.express as px
import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import plotly.graph_objects as go
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error, mean_squared_error
from sklearn.preprocessing import StandardScaler
from sklearn.neural_network import MLPRegressor

In [43]:
base = pd.read_csv('house_prices.csv')
base.drop('date', axis='columns', inplace=True) #REMOVENDO A COLUNA EM FORMATO DE DATA
X_casas = base.iloc[:,2:18].values
y_casas = base.iloc[:,1].values
XcasasTreino, XcasasTeste, YcasasTreino, YcasasTeste = train_test_split(X_casas,y_casas, test_size = 0.3, random_state=0)
XcasasTreino,YcasasTreino

(array([[ 4.00000e+00,  1.50000e+00,  1.39000e+03, ...,  9.81330e+04,
          4.77224e+01, -1.22332e+02],
        [ 3.00000e+00,  1.50000e+00,  1.45000e+03, ...,  9.81330e+04,
          4.77725e+01, -1.22349e+02],
        [ 5.00000e+00,  2.75000e+00,  2.86000e+03, ...,  9.80520e+04,
          4.77082e+01, -1.22104e+02],
        ...,
        [ 3.00000e+00,  2.25000e+00,  2.36000e+03, ...,  9.80420e+04,
          4.73856e+01, -1.22158e+02],
        [ 4.00000e+00,  2.00000e+00,  2.37000e+03, ...,  9.80010e+04,
          4.72831e+01, -1.22279e+02],
        [ 4.00000e+00,  2.25000e+00,  2.38000e+03, ...,  9.80080e+04,
          4.76126e+01, -1.22120e+02]]),
 array([400000., 430000., 720000., ..., 431000., 411000., 699900.]))

In [44]:
scalerX = StandardScaler()
XcasasTreino = scalerX.fit_transform(XcasasTreino)
scalerY = StandardScaler()
YcasasTreino = scalerY.fit_transform(YcasasTreino.reshape(-1,1))
XcasasTreino,YcasasTreino

(array([[ 0.67170039, -0.79711466, -0.74522967, ...,  1.03727271,
          1.17348387, -0.83797629],
        [-0.38696772, -0.79711466, -0.68028398, ...,  1.03727271,
          1.53476983, -0.95879989],
        [ 1.7303685 ,  0.82292131,  0.84593978, ..., -0.48008241,
          1.07108346,  0.78248142],
        ...,
        [-0.38696772,  0.17490692,  0.30472568, ..., -0.66741021,
         -1.25528083,  0.3986888 ],
        [ 0.67170039, -0.14910028,  0.31554996, ..., -1.43545415,
         -1.99443873, -0.46129094],
        [ 0.67170039,  0.17490692,  0.32637425, ..., -1.3043247 ,
          0.38168351,  0.66876509]]),
 array([[-0.38454326],
        [-0.3024967 ],
        [ 0.49062008],
        ...,
        [-0.29976181],
        [-0.35445952],
        [ 0.43564888]]))

In [45]:
XcasasTeste = scalerX.transform(XcasasTeste)
YcasasTeste = scalerY.transform(YcasasTeste.reshape(-1,1))
XcasasTeste,YcasasTeste

(array([[-1.44563583, -0.79711466, -0.70193254, ...,  0.88741047,
          1.17204161, -0.53947092],
        [ 0.67170039,  1.47093569,  2.80513482, ..., -1.36052304,
          0.54321655,  0.35604518],
        [-1.44563583, -1.76913625, -0.69110826, ...,  0.55022044,
          0.80065984, -1.06540895],
        ...,
        [-0.38696772,  0.49891411,  0.07741576, ..., -0.36768574,
         -0.78077751,  0.88909048],
        [-0.38696772, -0.47310747, -0.64781113, ..., -0.854738  ,
         -1.39878563, -0.46839822],
        [-0.38696772, -1.44512905, -0.82099964, ...,  0.26922876,
         -1.78603226,  0.22100704]]),
 array([[-0.66623646],
        [ 2.83715179],
        [ 0.05878167],
        ...,
        [-0.43924097],
        [-0.74554814],
        [-0.91511104]]))

In [55]:
# 16 entradas, para 9 neuronios na primeira camada, depois mais 9 na segunda camada e por fim, 1 neuronio
regressor = MLPRegressor(max_iter=1000, hidden_layer_sizes=(9,9))
regressor.fit(XcasasTreino,YcasasTreino.ravel())

MLPRegressor(hidden_layer_sizes=(9, 9), max_iter=1000)

In [56]:
regressor.score(XcasasTreino,YcasasTreino)

0.8915188589965738

In [57]:
regressor.score(XcasasTeste,YcasasTeste)

0.8776930685601313

In [58]:
previsoes = regressor.predict(XcasasTeste)
previsoes

array([-0.43280882,  3.40873397,  0.06063942, ..., -0.51043783,
       -0.84180693, -0.8492237 ])

In [59]:
YcasasTeste

array([[-0.66623646],
       [ 2.83715179],
       [ 0.05878167],
       ...,
       [-0.43924097],
       [-0.74554814],
       [-0.91511104]])

In [60]:
inversoY = scalerY.inverse_transform(YcasasTeste)
inversoY

array([[ 297000.],
       [1578000.],
       [ 562100.],
       ...,
       [ 380000.],
       [ 268000.],
       [ 206000.]])

In [61]:
invernoPrevisoes = scalerY.inverse_transform(previsoes.reshape(-1,1))
invernoPrevisoes

array([[ 382351.88975365],
       [1786996.7544794 ],
       [ 562779.27911393],
       ...,
       [ 353967.15083343],
       [ 232803.35538176],
       [ 230091.44323047]])

In [62]:
mean_absolute_error(inversoY,invernoPrevisoes)

75739.61880674415

Durante as aulas sobre regressão você aprendeu que pode utilizar a métrica score para avaliar o desempenho de um algoritmo de regressão, juntamente com o cálculo do mean_absolute_error para comparar os resultados previstos com os resultados reais. Para uma correta avaliação de um algoritmo você pode seguir os mesmos passos apresentados nas aulas sobre classificação, ou seja:

Utilizar validação cruzada ao invés de dividir a base em porções para treinamento e teste

Executar pelo menos 30 testes com cada algoritmo, utilizando o valor retornado pelo score (opcionalmente você pode usar o mean_absolute_error)

Construir a planilha com os resultados, calculando a média dos 30 testes de cada algoritmo

Fazer os testes de Friedmann e Nemenyi para verificar se existe diferença estatística significativa entre os resultados

Por fim, por meio dos resultados escolher o melhor algoritmo

No módulo sobre classificação também foram apresentados os conceitos sobre combinação e rejeição de classificadores, que também podem ser utilizados para problemas de regressão. As diferenças são:

Na combinação de regressores, você deve obter o valor da previsão numérica de cada algoritmo e calcular a média para calcular o valor final

Na rejeição de regressores, você pode estipular um valor mínimo para o mean_absolute_error, e caso o valor previsto seja maior que esse parâmetro você pode ignorar a resposta do regressor