In [ ]:
!pip install plotly --upgrade

In [ ]:
import plotly.express as px
import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import plotly.graph_objects as go

In [ ]:
base = pd.read_csv('plano_saude2.csv')

In [ ]:
base

idade  custo
0     18    470
1     23    520
2     28    630
3     33    830
4     38   1150
5     43   1530
6     48   2040
7     53   3080
8     58   5100
9     63  10100

In [ ]:
X = base.iloc[:, 0:1].values
X

array([[18],
       [23],
       [28],
       [33],
       [38],
       [43],
       [48],
       [53],
       [58],
       [63]])

In [ ]:
Y = base.iloc[:, 1].values
Y

array([  470,   520,   630,   830,  1150,  1530,  2040,  3080,  5100,
       10100])

In [ ]:
from sklearn.preprocessing import PolynomialFeatures

poly = PolynomialFeatures(degree = 4) #numero de vezes que os atributos serão replicados e elevados TESTE COM OUTROS DEGRAIS
X_poly = poly.fit_transform(X)

In [ ]:
X.shape

(10, 1)

In [ ]:
18 * 18

324

In [ ]:
X_poly #segundo valor é o valor original, e o terceiro é o quadrado dele.

array([[1.0000000e+00, 1.8000000e+01, 3.2400000e+02, 5.8320000e+03,
        1.0497600e+05],
       [1.0000000e+00, 2.3000000e+01, 5.2900000e+02, 1.2167000e+04,
        2.7984100e+05],
       [1.0000000e+00, 2.8000000e+01, 7.8400000e+02, 2.1952000e+04,
        6.1465600e+05],
       [1.0000000e+00, 3.3000000e+01, 1.0890000e+03, 3.5937000e+04,
        1.1859210e+06],
       [1.0000000e+00, 3.8000000e+01, 1.4440000e+03, 5.4872000e+04,
        2.0851360e+06],
       [1.0000000e+00, 4.3000000e+01, 1.8490000e+03, 7.9507000e+04,
        3.4188010e+06],
       [1.0000000e+00, 4.8000000e+01, 2.3040000e+03, 1.1059200e+05,
        5.3084160e+06],
       [1.0000000e+00, 5.3000000e+01, 2.8090000e+03, 1.4887700e+05,
        7.8904810e+06],
       [1.0000000e+00, 5.8000000e+01, 3.3640000e+03, 1.9511200e+05,
        1.1316496e+07],
       [1.0000000e+00, 6.3000000e+01, 3.9690000e+03, 2.5004700e+05,
        1.5752961e+07]])

In [ ]:
from sklearn.linear_model import LinearRegression

regressor = LinearRegression()

In [ ]:
regressor.fit(X_poly, Y)

LinearRegression()

In [ ]:
regressor.intercept_  #B0

16561.97463791193

In [ ]:
regressor.coef_ #Bn's

array([ 0.00000000e+00, -2.12242253e+03,  9.90404199e+01, -1.95058276e+00,
        1.40792541e-02])

In [ ]:
novo = poly.transform([[40]])
novo

array([[1.00e+00, 4.00e+01, 1.60e+03, 6.40e+04, 2.56e+06]])

In [ ]:
regressor.predict(novo)

array([1335.33958015])

In [ ]:
previsoes = regressor.predict(X_poly)
previsoes

array([ 549.65035464,  345.85081575,  616.53845992,  975.8391595 ,
       1249.06759853, 1472.7272727 , 1894.51048941, 2973.2983677 ,
       5379.16083828, 9993.35664357])

In [ ]:
grafico = px.scatter(x = X.ravel(), y = Y) #GRAFICO DE DISPERSÃO
grafico.add_scatter(x = X.ravel(), y = previsoes, name = 'Regressão Poly')
grafico.show()

BASE DAS CASAS

In [ ]:
base = pd.read_csv('house_prices.csv')

In [ ]:
base.drop('date', axis='columns', inplace=True) #REMOVENDO A COLUNA EM FORMATO DE DATA

In [ ]:
Xcasas = base.iloc[:,2:18].values
Ycasas = base.iloc[:,1].values


In [ ]:
from sklearn.model_selection import train_test_split

XcasasTreino, XcasasTeste, YcasasTreino, YcasasTeste = train_test_split(Xcasas,Ycasas, test_size = 0.3, random_state=0)

In [ ]:
XcasasTreino.shape, YcasasTreino.shape

((15129, 16), (15129,))

In [ ]:
XcasasTeste.shape, YcasasTeste.shape

((6484, 16), (6484,))

In [ ]:
poly = PolynomialFeatures(degree = 2)
XpolyTreino = poly.fit_transform(XcasasTreino)
XpolyTeste = poly.fit_transform(XcasasTeste)

In [ ]:
XpolyTreino.shape, XpolyTeste.shape

((15129, 153), (6484, 153))

In [ ]:
regressor = LinearRegression()

regressor.fit(XpolyTreino,YcasasTreino)

LinearRegression()

In [ ]:
regressor.score(XpolyTreino,YcasasTreino)

0.8179232870746764

In [ ]:
regressor.score(XpolyTeste,YcasasTeste)

0.8152794736736874

In [ ]:
previsoes = regressor.predict(XpolyTeste)
previsoes

array([ 386125.93736267, 1990545.15264893,  578956.99684906, ...,
        433101.52619934,  234034.0341568 ,  123888.63271332])

In [ ]:
YcasasTeste

array([ 297000., 1578000.,  562100., ...,  380000.,  268000.,  206000.])

In [ ]:
from sklearn.metrics import mean_absolute_error, mean_squared_error

In [ ]:
mean_absolute_error(YcasasTeste, previsoes) #MAE #Diferenças reais

101238.08202969447

ARVORES DE REGRESSÃO

BASE DE PLANO DE SAUDE

In [ ]:
from sklearn.tree import DecisionTreeRegressor

base = pd.read_csv('plano_saude2.csv')
X = base.iloc[:, 0:1].values
Y = base.iloc[:, 1].values
regressorArvore = DecisionTreeRegressor()

regressorArvore.fit(X,Y)
regressorArvore.score(X,Y)

1.0

In [ ]:
previsoes = regressorArvore.predict(X)
previsoes

array([  470.,   520.,   630.,   830.,  1150.,  1530.,  2040.,  3080.,
        5100., 10100.])

In [ ]:
grafico = px.scatter(x = X.ravel(), y = Y) #GRAFICO DE DISPERSÃO
grafico.add_scatter(x = X.ravel(), y = previsoes, name = 'Regressão Arvore')
grafico.show()

In [ ]:
X_teste_arvore = np.arange(min(X), max(X), 0.1) #GERANDO UM DATASET DE TESTE FALSO
X_teste_arvore

<ipython-input-39-cd9c05b8f388>:1: DeprecationWarning:

Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)



array([18. , 18.1, 18.2, 18.3, 18.4, 18.5, 18.6, 18.7, 18.8, 18.9, 19. ,
       19.1, 19.2, 19.3, 19.4, 19.5, 19.6, 19.7, 19.8, 19.9, 20. , 20.1,
       20.2, 20.3, 20.4, 20.5, 20.6, 20.7, 20.8, 20.9, 21. , 21.1, 21.2,
       21.3, 21.4, 21.5, 21.6, 21.7, 21.8, 21.9, 22. , 22.1, 22.2, 22.3,
       22.4, 22.5, 22.6, 22.7, 22.8, 22.9, 23. , 23.1, 23.2, 23.3, 23.4,
       23.5, 23.6, 23.7, 23.8, 23.9, 24. , 24.1, 24.2, 24.3, 24.4, 24.5,
       24.6, 24.7, 24.8, 24.9, 25. , 25.1, 25.2, 25.3, 25.4, 25.5, 25.6,
       25.7, 25.8, 25.9, 26. , 26.1, 26.2, 26.3, 26.4, 26.5, 26.6, 26.7,
       26.8, 26.9, 27. , 27.1, 27.2, 27.3, 27.4, 27.5, 27.6, 27.7, 27.8,
       27.9, 28. , 28.1, 28.2, 28.3, 28.4, 28.5, 28.6, 28.7, 28.8, 28.9,
       29. , 29.1, 29.2, 29.3, 29.4, 29.5, 29.6, 29.7, 29.8, 29.9, 30. ,
       30.1, 30.2, 30.3, 30.4, 30.5, 30.6, 30.7, 30.8, 30.9, 31. , 31.1,
       31.2, 31.3, 31.4, 31.5, 31.6, 31.7, 31.8, 31.9, 32. , 32.1, 32.2,
       32.3, 32.4, 32.5, 32.6, 32.7, 32.8, 32.9, 33

In [ ]:
X_teste_arvore = X_teste_arvore.reshape(-1,1)
X_teste_arvore.shape

(450, 1)

In [ ]:
grafico = px.scatter(x = X.ravel(), y = Y) #GRAFICO DE DISPERSÃO
grafico.add_scatter(x = X_teste_arvore.ravel(), y = regressorArvore.predict(X_teste_arvore), name = 'Regressão Arvore')
grafico.show()

In [ ]:
regressorArvore.predict([[40]])

array([1150.])

BASE DAS CASAS COM ARVORE DE REGRESSÃO

In [ ]:
base = pd.read_csv('house_prices.csv')
base

id             date     price  bedrooms  bathrooms  \
0      7129300520  20141013T000000  221900.0         3       1.00   
1      6414100192  20141209T000000  538000.0         3       2.25   
2      5631500400  20150225T000000  180000.0         2       1.00   
3      2487200875  20141209T000000  604000.0         4       3.00   
4      1954400510  20150218T000000  510000.0         3       2.00   
...           ...              ...       ...       ...        ...   
21608   263000018  20140521T000000  360000.0         3       2.50   
21609  6600060120  20150223T000000  400000.0         4       2.50   
21610  1523300141  20140623T000000  402101.0         2       0.75   
21611   291310100  20150116T000000  400000.0         3       2.50   
21612  1523300157  20141015T000000  325000.0         2       0.75   

       sqft_living  sqft_lot  floors  waterfront  view  ...  grade  \
0             1180      5650     1.0           0     0  ...      7   
1             2570      7242     2.0           0     0  ...      7   
2              770     10000     1.0           0     0  ...      6   
3             1960      5000     1.0           0     0  ...      7   
4             1680      8080     1.0           0     0  ...      8   
...            ...       ...     ...         ...   ...  ...    ...   
21608         1530      1131     3.0           0     0  ...      8   
21609         2310      5813     2.0           0     0  ...      8   
21610         1020      1350     2.0           0     0  ...      7   
21611         1600      2388     2.0           0     0  ...      8   
21612         1020      1076     2.0           0     0  ...      7   

       sqft_above  sqft_basement  yr_built  yr_renovated  zipcode      lat  \
0            1180              0      1955             0    98178  47.5112   
1            2170            400      1951          1991    98125  47.7210   
2             770              0      1933             0    98028  47.7379   
3            1050            910      1965             0    98136  47.5208   
4            1680              0      1987             0    98074  47.6168   
...           ...            ...       ...           ...      ...      ...   
21608        1530              0      2009             0    98103  47.6993   
21609        2310              0      2014             0    98146  47.5107   
21610        1020              0      2009             0    98144  47.5944   
21611        1600              0      2004             0    98027  47.5345   
21612        1020              0      2008             0    98144  47.5941   

          long  sqft_living15  sqft_lot15  
0     -122.257           1340        5650  
1     -122.319           1690        7639  
2     -122.233           2720        8062  
3     -122.393           1360        5000  
4     -122.045           1800        7503  
...        ...            ...         ...  
21608 -122.346           1530        1509  
21609 -122.362           1830        7200  
21610 -122.299           1020        2007  
21611 -122.069           1410        1287  
21612 -122.299           1020        1357  

[21613 rows x 21 columns]

In [ ]:
base.drop('date', axis='columns', inplace=True) #REMOVENDO A COLUNA EM FORMATO DE DATA
X_casas = base.iloc[:,2:18].values
y_casas = base.iloc[:,1].values
XcasasTreino, XcasasTeste, YcasasTreino, YcasasTeste = train_test_split(X_casas,y_casas, test_size = 0.3, random_state=0)

In [ ]:
XcasasTreino.shape, YcasasTreino.shape

((15129, 16), (15129,))

In [ ]:
XcasasTeste.shape,  YcasasTeste.shape

((6484, 16), (6484,))

In [ ]:
regressoArvore = DecisionTreeRegressor()
regressoArvore.fit(XcasasTreino,YcasasTreino)

DecisionTreeRegressor()

In [ ]:
regressoArvore.score(XcasasTreino,YcasasTreino)

0.9992712177726063

In [ ]:
regressoArvore.score(XcasasTeste,YcasasTeste)

0.7286515383588554

In [ ]:
previsoes = regressoArvore.predict(XcasasTeste)
previsoes

array([ 289000., 1835000.,  507000., ...,  289000.,  215000.,  201000.])

In [ ]:
mean_absolute_error(YcasasTeste, previsoes) #MAE #Diferenças reais

99634.84253547194